Logger:
  Driver: zap
  # 日志等级, trace, debug, info, warn, error, fatal
  Level: debug
  WriteTo: [
    { Name: console,
      Args: {
      }
    }
  ]

entryPoint:
  address: 127.0.0.1
  port: 45678

#=============================dynamic
providers:
  file:
    watch: true
    filename: config/settings.debug.yml

Databases:
  DbAlisName: MainDb
  Driver: mysql
  MaxIdleCons: 10
  MaxOpenCons: 50
  Source: root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  Registers:
    - Sources: ["root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms"]

balanceMode:
  balance: wwr
globalMiddleware:
  - Cors
http:
  services:
    myBlogService:
      service: testBlogService
      routers:
        path: /api/blogs
        method: "*"
        proxyPath: /blogs
      servers:
        - host: 127.0.0.1
          port: 6785