providers:
  file:
    watch: false
    filename: config/gateway-dynamic.yml

entryPoint:
  address: 127.0.0.1
  port: 45678

Databases:
  DbAlisName: MainDb
  Driver: mysql
  MaxIdleCons: 10
  MaxOpenCons: 50
  Source: root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  Registers:
      - Sources: ["root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms"]

Logger:
  Driver: zap
  # 日志等级, trace, debug, info, warn, error, fatal
  Level: debug
  WriteTo: [
    { Name: console,
      Args: {
      }
    }
  ]