Logger:
  Driver: zap
  # 日志等级, trace, debug, info, warn, error, fatal
  Level: debug
  WriteTo: [
    { Name: console,
      Args: {
      }
    }
  ]

entryPoint:
  address: 127.0.0.1
  port: 12000

#=============================dynamic
providers:
  file:
    watch: true
    filename: config/settings.debug.yml

Databases:
  DbAlisName: MainDb
  Driver: mysql
  MaxIdleCons: 10
  MaxOpenCons: 50
  Source: root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  Registers:
      - Sources: ["root:root@tcp(127.0.0.1:3306)/gateway?charset=utf8&parseTime=True&loc=Local&timeout=1000ms"]

balanceMode:
  balance: wwr
globalMiddleware:
  - Cors
easyServiceRoute:
  services:
    myBlogService:
        myBlogServiceHttp:
           balanceMode:  wwr
           handler: http
           routers:
             - path: "/api/*filepath"
               methods: ["POST","DELETE","GET","PUT","OPTIONS"]
#             - path: "/api/Account/Login"
#               methods: ["POST"]
           servers:
             - host: 127.0.0.1
               port: 19002
               weight: 1
             - host: 127.0.0.1
               port: 19002
               weight: 2
#         myBlogServiceWebSocket:
#           serviceName:
#      routers:
#        path: "/api/*filepath"
#        method: "*"
#        proxyPath:
#      servers:
#        - host: 121.196.220.148
#          port: 19002